language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz 
  - tar -zxf android-sdk_r21.1-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,4,"addon-google_apis-google-16" --no-ui --force
