language: java

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#selendroid"
    on_success: always
    on_failure: always
    use_notice: true
  
branches:
  only:
    - master

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 python-lxml
  - wget http://dl.google.com/android/android-sdk_r22.6-linux.tgz
  - tar -zxf android-sdk_r22.6-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/19.0.3/
  - echo "y" | android update sdk --filter tools,platform-tools,build-tools-19.0.3,android-16 --no-ui --force
  # Maven 3.1.1
  - wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  - tar xvf apache-maven-3.1.1-bin.tar.gz > /dev/null
  - export MVN_HOME=`pwd`/apache-maven-3.1.1
  - export PATH=${MVN_HOME}/bin/:${PATH}
  - mvn --version  
  - "git clone -b travis `git config --get remote.origin.url` target/travis"

script: 
  - "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml"


env:
  global:
    - secure: "qOCTIN+N9lYVx/rp7Qu5xcyaFPLsf64UYSOY5dq+4jOx5vokQfb0vwFxKyDJcUD7ow3GMhw11280HE2OZ3Xk+1xRGWND5Axhey8BPOjqT9D+vjKY2o2Q2ZmUbBTapL/lDixjnV9Gk/bJLytPLNaaA7S/HNfp0g03bWhLanz5fgg="
    - secure: "BzwsXUidLx7X733KzZDwvuXsIiFD0WazDABk8FM3BuvkJnGd8xp84A0ZwZ76PYvrxWp/MncyaOytkrnNA86rnBmpWvcnWzEuBVoDY/cEc4q1SnLjgsRByanNBPoYopFHAVRI2zvkU8hSBVFZC2+ABi3vpNhgYr0LtBhZouBTX5E="
